[tool.poetry]
name = "asio-jam"
version = "0.1.0"
description = ""
authors = ["Martin Jul <martin@mjul.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
